### ISSUE TITLE
(feature request)larger list

### ISSUE THREAD

**Issue by NeonLightning** [RetroHursty69/es-theme-OdroidHursty#1]
is there a chance of making this theme use a larger gamelist? the main menu is beautiful but i would like to see more games listed at once.

**Comment by RetroHursty69** [comment]
Mate, whilst I agree the design doesn't really allow it. I could do that but I will have to lose the game description. What if I reduced the font size of the gamelist?

**Comment by NeonLightning** [comment]
that might work :)
